version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/fah-break:latest@sha256:edb6823711bc989b66c8921b901a915e1e1c1db7284cae7aa52210063f485b8c
    restart: unless-stopped
    volumes:
      - ${NGINX_HOME}/logs:/mnt/nginx-logs
